apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: default
parameters:
    encrypted: "false"
    type: gp2
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: false