apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
  - name: postgresql-secrets
    literals:
      - POSTGRES_PASSWORD=tes6Aev8
  
resources:
  - storageclass-aws.yaml
  - pg-svc.yaml
  - pg-sfs.yaml